name: mini-text
base: core24
adopt-info: mini-text
grade: stable
confinement: strict
platforms:
  amd64:
  arm64:

parts:
  mini-text:
    plugin: meson
    source: https://github.com/Nokse22/mini-text.git
    source-tag: 'v0.2.2'
    source-depth: 1
    parse-info: [ usr/share/appdata/io.github.nokse22.minitext.appdata.xml ]
    build-snaps:
      - blueprint-compiler/latest/edge
    meson-parameters:
      - --prefix=/snap/mini-text/current/usr
    override-build: |
      craftctl default
      sed -e '1c#!/usr/bin/env python3' -i ${CRAFT_PART_INSTALL}/snap/mini-text/current/usr/bin/mini-text
      chmod +x $CRAFT_PART_INSTALL/snap/mini-text/current/usr/bin/mini-text
    organize:
      snap/mini-text/current: .

slots:
  mini-text:
    interface: dbus
    bus: session
    name: io.github.nokse22.minitext

apps:
  mini-text:
    command: usr/bin/mini-text
    extensions: [ gnome ]
    common-id: io.github.nokse22.minitext
    desktop: usr/share/applications/io.github.nokse22.minitext.desktop
